name: Buildto Gitee
on:
  push:
    branches:
      - main
  trigger: manual  # Gitee Go 使用 trigger: manual 而不是 manual: true

env:
  IMAGE_NAME: xianyu-auto-reply
  IMAGE_TAG: v1.0.4
  REGISTRY_URL: registry.gitee.com

jobs:
  buildx:
    name: Build Multi-Platform Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitee Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ gitee.owner }}
          password: ${{ secrets.GITEE_TOKEN }}

      - name: Build and push multi-platform images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY_URL }}/${{ gitee.owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY_URL }}/${{ gitee.owner }}/${{ env.IMAGE_NAME }}:latest
