version: '2.0'
name: docker-build-push
displayName: Docker构建和推送
triggers:
  push:
    branches:
      - main
  manual: true  # 启用手动触发

stages:
  - name: build
    strategy:
      matrix:
        platform: [ubuntu-latest]
    steps:
      - checkout:
          alias: code
      
      - step: buildx-setup
        type: public:docker_setup_buildx
        version: 1.0
      
      - step: docker-login
        type: public:docker_login
        version: 1.0
        image: docker
        envs:
          DOCKER_USER: ${{ gitee.owner }}
          DOCKER_PASSWORD: ${{ secrets.GITEE_TOKEN }}
          DOCKER_REGISTRY: registry.gitee.com
      
      - step: build-push
        type: public:docker_build_push
        version: 1.0
        image: docker
        commands:
          - docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t registry.gitee.com/${{ gitee.owner }}/xianyu-auto-reply:v1.0.2 \
            -t registry.gitee.com/${{ gitee.owner }}/xianyu-auto-reply:latest \
            .
