name: Build and Push to Gitee

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: xianyu-auto-reply
  IMAGE_TAG: v1.0.4
  GITEE_REGISTRY: registry.cn-north-1.gitee.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitee Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEE_REGISTRY }}
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_TOKEN }}

      - name: Build and push to Gitee
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.GITEE_REGISTRY }}/${{ secrets.GITEE_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.GITEE_REGISTRY }}/${{ secrets.GITEE_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.GITEE_REGISTRY }}/${{ secrets.GITEE_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.GITEE_REGISTRY }}/${{ secrets.GITEE_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
